// <auto-generated />
namespace OgrenciBilgiSistemi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class OgrenciIdIdentityYapp : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(OgrenciIdIdentityYapp));
        
        string IMigrationMetadata.Id
        {
            get { return "202512190829401_OgrenciIdIdentityYapp"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
