// <auto-generated />
namespace OgrenciBilgiSistemi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class VeritabaniOlusturma : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(VeritabaniOlusturma));
        
        string IMigrationMetadata.Id
        {
            get { return "202512181137151_VeritabaniOlusturma"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
